lang = {
    DEFAULT: (key) => `${key} ještě nebylo přeloženo do en-US.`,
    DEFAULT_LANGUAGE: 'Výchozí Jazyk',
    // PREFIX COMMAND
    PREFIX_REMINDER: (prefix = `@${this.client.user.tag}`) => `Aktuální prefix${Array.isArray(prefix) ?
        `i na tomto serveru jsou: ${prefix.map(pre => `\`${pre}\``).join(', ')}` :
        ` na tomto serveru je nastaveno na: \`${prefix}\``
    }`,
    PREFIX_SET: (prefix) => `Prefix byl změněn na \`${prefix}\``,
    CURRENT_PREFIX: (cprefix) => `Aktuální prefix je: \`${cprefix}\``,
    PREFIX_DESCRIPTION: 'Změní/ukáže prefix na tomto serveru',
    PREFIX_LENGTH: '**Nemůžeš nastavit prefix delší než 10 znaků!**',
    // SHIT
    COOLDOWN_TITLE: 'Cooldown',
    COOLDOWN: (remaining) => `Musíš ještě počkat ${remaining} sekundu${remaining != 1 ? '' : 'u'}.`,
    COMMAND_DISABLED_SERVER: 'Tento příkaz byl vypnut na tomto serveru.',
    COMMAND_DISABLED_GLOBAL: 'Tento příkaz momentálně není dostupný.',
    MISSING_BOTPERMS: (missing) => `Nemám dostatečné práva, abych dokončil tento příkaz, chybí mi: **${missing}**.`,
    NSFW: 'Tento command může být použit pouze v NSFW channelu!',
    NO_PERMISSIONS: 'Nemáš práva na to použít tento příkaz!',
    MISSING_REQUIRED_SETTINGS: (settings) => `Tento server nemá **${settings.join(', ')}** server nastavení a proto tento command nemůže být dokončen.`,
    RUNIN: (types) => `This command is only available in \`${types}\` channels!`,
    RUNIN_NONE: (name) => `Command \`${name}\` is not configured to run in any channel.`,
    // EVAL
    EVAL_DESCRIPTION: 'Vyhodotí daný kód',
    EVAL_ERROR: (time, output, type) => `**Error**:${output}\n**Typ**:${type}\n${time}`,
    EVAL_OUTPUT: (time, output, type) => `**Output**:${output}\n**Typ**:${type}\n${time}`,
    EVAL_SENDFILE: (time, type) => `Výstup byl moc dlouhý... výsledek poslán v souboru.\n**Typ**:${type}\n${time}`,
    EVAL_CONSOLE: (time, type) => `Výstup byl moc dlouhý... výsledek poslán do konzole.\n**Typ**:${type}\n${time}`,
    // PING
    PING: '**Pong!**\nRoundtrip took: \`Vypočítávám...\`.\nHeartbeat: \`Vypočítávám...\`.\nDatabáze: \`Vypočítávám...\`.\nREST: \`Vypočítávám...\`.',
    PONG: (diff, ping, db, rest) => `**Pong!**\nRoundtrip trval: \`${diff}ms\`.\nHeartbeat: \`${ping}ms\`.\nDatabáze: \`${db}ms\`.\nREST: \`${rest}\`.`,
    PING_DESCRIPTION: 'Pong!',
    // INVITE
    INVITE_DESCRIPTION: 'Přidejte Bass do vašeho serveru!',
    BASS_INVITE: 'Přidejte Bass do vašeho serveru!',
    // INFO
    INFO_DESCRIPTION: 'Info o bassovi',
    // HELP
    HELP_DESCRIPTION: 'Tato zpráva',
    HELP_NO_EXTENDED: 'Žádná rozšířená pomoc není dostupná.',
    HELP_USAGE: (usage) => `Použití :: ${usage}`,
    HELP_EXTENDED: 'Rozšířená Pomoc ::',
    HELP_BOT_OWNER_ONLY: `Majitel bota`,
    HELP_MANAGE_GUILD: `Spravovat server`,
    HELP_SERVER_OWNER: `Majitel serveru`,
    HELP_SYNTAX: (prefix) => `${prefix}Příkaz - Popis *(Nutné práva)*\npro získání informací o použití commandu napište ${prefix}příkaz a ukáže vám to správné použití\nNa příklad: ${prefix}volume`,
    //HELP_SYNTAX: (prefix) => `${prefix}command - Description *(Required permissions)*\nTo get informations about command usage do ${prefix}help (commandname)\nUsing command that requires args, without giving them will also give command usage info`,
    HELP_COMMANDS_STRING: `Příkazy`,
    HELP_COMMAND_NOT_FOUND: (command) => `Příkaz \`${command}\` nebyl nalezen.`,
    HELP_TITLE: 'Bass pomoc',
    HELP_LINKS: 'Odkazy',
    HELP_SUPPORT_SERVER: 'Podpora',
    HELP_INVITE: 'Invite',
    HELP_VOTE: 'Hlasování',
    // STATS
    STATS_DESCRIPTION: 'Ukáže statistiky o Bass',
    CLUSTER: 'Cluster',
    ERROR: 'Error',
    SHARDS: 'Shardů',
    SERVERS: 'Serverů',
    USERS: 'Uživatelů',
    CONNECTIONS: 'Připojení',
    PLAYERS: 'Hráčů',
    TOTAL: 'Celkově',
    CLUSTERS: 'Clusterů',
    //EVENTS_RECIEVED: 'Events recieved',
    //COMMANDS_USED: 'Commands used',
    EVENTS_RECIEVED: 'Eventy',
    COMMANDS_USED: 'Příkazy',
    MESSAGES_RECIEVED: 'Přijaté zprávy',
    MESSAGES_SENT: 'Poslané zptávy',
    TOOK: (time) => `Travalo ${time}`,
    STATS: 'Statistiky Bass',
    // LANG
    LANG_NOT_FOUND: (lang, langsavailable) => `Jazyk \`${lang}\` nebyl nalezen.\nDostupné jazyky: \`${langsavailable}\``,
    LANG_LANGUAGE_SET: (lang) => `Jazyk byl změněn na \`${lang}\`!`,
    CURRENT_LANGUAGE: (clang, langsavailable) => `**Momentální jazyk:** \`${clang}\`\n\nDostupné jazyky: \`${langsavailable}\``,
    LANG_DESCRIPTION: 'Změní/Ukáže jazyk serveru',
    // TRANSLATORS / CONTRIBUTORS
    TRANSLATORS_DESCRIPTION: 'Ukáže každého překladatele co překládal do ostatních jazyků',
    CONTRIBUTORS_DESCRIPTION: 'Ukáže každého kdo pomáhal Bass projektu',
    // SAY
    SAY_DESCRIPTION: 'Bass zopakuje danou zprávu',
    // SHARD
    SHARD_DESCRIPTION: 'Ukáže info o shardech/clusterech',
    EMBED_SHARD_DESCRIPTION: (shard, shards, cluster, clusters) => `Tento server běží na shardu \`${shard}/${shards}\` a clusteru \`${cluster}/${clusters}\``,
    // SUPPORT
    BASS_SUPPORT_SERVER: 'Bass server podpory',
    // MUSIC
    NODE_BUSY: 'Omlouváme se, ale audio node na tomto serveru **je momentálně vytížený**, prosím počkejte pár vteřin.',
    NODE_NOTHING_PLAYING: '**Nic nehraje na tomto serveru.**\nMožná něco pusťe?',
    NODE_NOTHING_PLAYED: '**Nic nebylo přehráno.**',
    NODE_PROCESSING: 'Audio node zpracovává váš požadavek...',
    H4DEEP_DESCRIPTION: 'Přepne 4deep audio filtr',
    NODE_4DEEP_ENABLED: '**Spuštěn filtr** `4deep`.',
    NODE_4DEEP_DISABLED: '**Vypnut filtr** `4deep`.',
    H8D_DESCRIPTION: 'Přepne 8D audio filtr',
    NODE_8D_ENABLED: '**Spuštěn filtr** `8D`.',
    NODE_8D_DISABLED: '**Vypnut filtr** `8D`.',
    ECHO_DESCRIPTION: 'Přepne echo audio filtr',
    NODE_ECHO_ENABLED: '**Spušťen filtr** `Echo`.',
    NODE_ECHO_DISABLED: '**Vypnut filtr** `Echo`.',
    NIGHTCORE_DESCRIPTION: 'Přepne nightcore audio filtr',
    NODE_NIGHTCORE_ENABLED: '**Spuštěn filtr** `Nightcore`.',
    NODE_NIGHTCORE_DISABLED: '**vypnut filtr** `Nightcore`.',
    VAPORWAVE_DESCRIPTION: 'Přepne vaporwave audio filtr',
    NODE_VAPORWAVE_ENABLED: '**Spuštěn filtr** `Vaporwave`.',
    NODE_VAPORWAVE_DISABLED: '**Vypnut filtr** `Vaporwave`.',
    CHORUS_DESCRIPTION: 'Přepne chorus audio filtr',
    NODE_CHORUS_ENABLED: '**Spuštěn filtr** `Chorus`.',
    NODE_CHORUS_DISABLED: '**Vypnut filtr** `Chorus`.',
    KARAOKE_DESCRIPTION: 'Přepne karaoke audio filtr',
    NODE_KARAOKE_ENABLED: '**Spuštěn filtr** `Karaoke`.',
    NODE_KARAOKE_DISABLED: '**Vypnut filtr** `Karaoke`.',
    PULSATOR_DESCRIPTION: 'Přepne pulsator audio filtr',
    NODE_PULSATOR_ENABLED: '**Spuštěn filtr** `Pulsator`.',
    NODE_PULSATOR_DISABLED: '**Vypnut filtr** `Pulsator`.',
    TREMOLO_DESCRIPTION: 'Přepne tremolo audio filtr',
    NODE_TREMOLO_ENABLED: '**Spuštěn filtr** `Tremolo`.',
    NODE_TREMOLO_DISABLED: '**Vypnut filtr** `Tremolo`.',
    HSURROUND_DESCRIPTION: 'Přepne surround audio filtr',
    NODE_SURROUND_ENABLED: '**Spuštěn filtr** `Surround`.',
    NODE_SURROUND_DISABLED: '**Vypnut filtr** `Surround`.',
    H8BIT_DESCRIPTION: 'Přepne 8bit audio filtr',
    NODE_8BIT_ENABLED: '**Spuštěn filtr** `8-bit`.',
    NODE_8BIT_DISABLED: '**Vypnut filtr** `8-bit`.',
    BITRATE_DESCRIPTION: 'Změní bitrate/kvalitu hudby',
    NODE_CHANGED_BITRATE: (amount) => `Bitrate byl změněn na \`${amount}kbps\``,
    NODE_INVALID_BITRATE: 'Prosím zadejte správný bitrate mezi \`8\` a \`512\` (kbps)',
    CLEAR_DESCRIPTION: 'Vymaže queue',
    CLEARED_QUEUE: 'Queue byla vymazána.',
    LOOP_DESCRIPTION: 'Opakuje song/queue',
    LOOP_SONG: '**Spuštěná song smyčka.**',
    LOOP_QUEUE: '**Spuštěná queue smyčka.**',
    LOOP_ALREADY_SONG: 'Song už je dávno ve smyčce!',
    LOOP_ALREADY_QUEUE: 'Queue už je dávno ve smyčce!',
    LOOP_DISABLED: '**Vypnutá smyčka.**',
    LOOP_INVALID: (prefix) => `**prosím dejte správnž typ smyčky ** \`(0 - vypnout, 1 - song, 2 - queue)\`\nNa příklad: \`${prefix}loop 2\``,
    NOWPLAYING_DESCRIPTION: 'Právě hrající song',
    NOWPLAYING: 'Právě hraje',
    PAUSE_DESCRIPTION: 'Stopne song',
    PAUSED: '**Stopnuto.**',
    RESUME_DESCRIPTION: 'Spustí song',
    RESUMED: '**Spuštěno.**',
    SHUFFLE_DESCRIPTION: 'Rozhází queue',
    SHUFFLE_SHUFFLING: '**Rozhazování queue...**',
    SHUFFLE_SHUFFLED: '**Queue rozhozena.**',
    QUEUE_DESCRIPTION: 'Ukáže queue',
    QUEUE_FETCHING: '**Načítám queue...**',
    QUEUE_MORE: (length) => `*.. a ${length} dalších*`,
    QUEUE_NOWPLAYING: 'Právě hraje',
    QUEUE_UPNEXT: 'Další',
    QUEUE_NOTHING: '**Nic**',
    QUEUE_LENGTH: 'Délka queue:',
    QUEUE_FILTERS: 'Filtry:',
    QUEUE_BASS_STRENGTH: 'Síla bass:',
    QUEUE_LOOP: '**Smyčka:**',
    QUEUE_SONG: 'Song:',
    QUEUE_YES: 'ano',
    QUEUE_NO: 'ne',
    QUEUE: 'Queue:',
    SKIP_DESCRIPTION: 'Přeskočí právě hrající song',
    SKIPPED: 'Přeskočeno',
    STOP_DESCRIPTION: 'Přestane hrát, smaže queue a opustí channel',
    STOPPED: 'stopnuto.',
    PREV_DESCRIPTION: 'Naposled hrané songy',
    RECENTLY_PLAYED: 'Posledně hrálo:',
    VOLUME_DESCRIPTION: 'Změní hlasitost',
    VOLUME_CHANGED: (prev, amount) => `**Hlasitost byl změněa z \`${prev}%\` n \`${amount}%\`.**`,
    VOLUME_SAME: (amount) => `**Hlasitost už je dávno nastavena na \`${amount}%\`!**`,
    GIVE_PROPER_VOLUME: (current) => `Prosím dejte správnou hlasitost mezi 0 a 500 (%)\nMomentální hlasitost je: \`${current}%\``,
    BASS_DESCRIPTION: 'Změní sílu basů',
    GIVE_PROPER_BASS: (current) => `Prosím dejte správnou hodnotu basů od 0 do 60 (dB)\nMomentální bass boost je: \`+${current}dB\``,
    NODE_BASS_CHANGED_DONATOR: (amount) => `**Změněna síla basů na ** \`+${amount}dB\`\nDěkuji za to, že podporuješ Bass!`,
    PLAY_DESCRIPTION: 'Přehraje song',
    JOINING_VC_ERROR: 'Nastala neznámá chyba když jsem se snažil napojit do tvého voice channelu.\nZkus to znovu.',
    QUEUED: (url, title) => `Přidáno [${title}](${url}) do queue.`,
    QUEUED_NOW: (url, title) => `[${title}](${url}) bude právě hrát.`,
    QUEUE_ENDED: 'Queue skončila, opustil jsem voice channel.',
    PLAYING_ERROR: (error) => `Error nastal při pokusu hrát hudbu.\nError zpráva: \`${error}\``,
    PLAYING_EVENT_WITH: (bass, volume, bitrate, filters) => `Bitrate: \`${bitrate}kbps\`, Hlasitost: \`${volume}%\`\nNastavené filtry: *${filters.join(', ') || '*-*'}*\nSíla bass boostu: \`+${bass}dB\``,
    PLAY_NO_SONG: 'Please give name or URL of song you want to play.',
    PLAY_NO_VC: 'You are not in a voice channel.',
    PLAY_OTHER_VC: 'You are not in same voice channel as me. Please join my voice channel and try again.',
    PLAY_NO_PERMS_SPEAK: 'I do not have permissions to speak in your voice channel.',
    PLAY_NO_PERMS_CONNECT: 'I do not have permissions to join your voice channel.',
    SEARCHING_ERROR: (error) => `Error occured while searching.\nError message: \`${error}\``,
    SEARCHING_NOT_FOUND: 'Nebyly nalezeny žádné výsledky.',
    PLAY_WRONGURL: 'URL vypadá jako neplatná.',
    PLAY_PROCESSING: 'Zpracovávám...',
    PLAY_BACKEND_ERROR: 'Backend pro zpracovávání výsledků/playlistů vypadá že je offline nebo navrátil error.\nProsím pošlete tuto informaci na náš support server **https://discord.gg/By3bvFc**!',
    PLAY_QUEUED_PLAYLIST: (size) => `Načteno ${size} song.`,
    LEAVING_VC: 'Stopuji přehrávání a opouštím voice channel za 15 sekund, pokud se nikdo nepřipojí.',
    LEFT_VC: 'Stopl jsem přehrávání a opustil voice channel, kvůli neaktivitě.',
    // SUPPORT
    SUPPORT_DESCRIPTION: 'Server podpory pro Bass',
    // TTS
    TTS_DESCRIPTION: 'Pošle text to speech soubor',
    TTS_WRONG_LANG: (langs, prefix) => `**Prosím zadejte podporované jazyky!**\nPodporované jazyky: \`${langs.join(', ')}\`\nPříklad: \`${prefix}tts Ahoj | cs\``,
    TTS_ERROR: 'Error nastal při načítání souboru.',
    TTS_WRONG_TXT_LENGTH: 'Délka textu musí být větší než 0 znaků a nesmí přesáhnout 200 znaků.',
    TTS_NO_ARGS: (prefix, langs) => `**Prosím zadejte text a jazyk pro generaci tts.**\nPříklad: \`${prefix}tts Ahoj | cs\`\nDostupné jazyky: \`${langs.join(', ')}\``,
    // IDK
    NONE_VC: 'Musíš být v mém voice channelu, aby jsi mohl použít tento příkaz!.',
    NONE_NVC: 'Nemůžu se napojit do tvého channelu!',
    NONE_NOVC: 'Nejsi ve voice channelu!',
    NONE_VCFULL: 'Tvůj voice channel je plný!',
    // RELOAD
    RELOAD_DESCRIPTION: 'Přenačte bass',
    RELOADED: 'Přenačteno',
    RELOADED_MESSAGE: (time) => `Bass byl úspěšně přenačten za ${time}.`,
    // VOTE
    VOTE_DESCRIPTION: 'Zkontroluje tvůj vote status/Dá vote link',
    YOU_VOTED: 'Hlasoval jsi!',
    YOU_DIDNT_VOTE: 'Nehlasoval jsi!',
    VOTED_MESSAGE: (mention, date, votes) => `Hlasoval jsi pro Bass posledních 12 hodin!\nDěkuji, ${mention} za podporování Bass hlasováním!\nhlasoval jsi v: \`${date}\`\nHlasoval jsi pro Bass ${votes}x.\n\n[Odkaz na hlasování](https://top.gg/bot/590948209925423123/vote)`,
    NOT_VOTED_MESSAGE: (date, votes) => `Nehlasoval jsi posledních 12 hodin :(\nTvůj poslední hlas byl v: \`${date}\`\nHlasoval jsi pro Bass ${votes}x.\n\nMůžeš hlasovat pro Bass [tady](https://top.gg/bot/590948209925423123/vote).`,
    // STUFF FOR NEW HELP
    HELP_DESCRIPTION_TITLE_STRING: (prefix) => `Prefix na tomto serveru je \`${prefix}\`\nPro získání více informací o příkazu zkuste ${prefix}help [příkaz] Príklad: ${prefix}help bass nebo ${prefix}help play`,
    HELP_PATREON: 'Patreon',
    HELP_CATEGORY: 'Kategorie',
    HELP_NAME: 'Jméno',
    HELP_ALIASES: 'Alias',
    HELP_CMD_DESCRIPTION: 'Popis',
    HELP_REQUIRED_PERMS: 'Potřebné práva',
    HELP_BOT_REQUIRED_PERMS: 'Potřebné práva bota Bass',
    HELP_COOLDOWN_TITLE: 'Cooldown',
    HELP_COOLDOWN: (uses, seconds) => `${uses} use${uses === 1 ? '' : 's'} per ${seconds} second${seconds === 1 ? '' : 's'}`,
    HELP_EXAMPLECOMMANDUSAGE: 'Example usage',
    HELP_EXAMPLECOMMANDUSAGE_OPTIONAL_REQUIRED: '() - dobrovolné, <> - nutné',
    HELP_EXAMPLEUSAGE: ' (příkaz)',
    EVAL_EXAMPLEUSAGE: ' <kód>',
    SAY_EXAMPLEUSAGE: ' <zpráva>',
    TTS_EXAMPLEUSAGE: ' <zpráva> | <kód jazyku>',
    LANG_EXAMPLEUSAGE: ' (jazyk)',
    PREFIX_EXAMPLEUSAGE: ' (prefix)',
    BITRATE_EXAMPLEUSAGE: ' <bitrate>',
    LOOP_EXAMPLEUSAGE: ' <typ smyčky>',
    PLAY_EXAMPLEUSAGE: ' <jméno songy nebo url>',
    VOLUME_EXAMPLEUSAGE: ' (hlasitost)',


    // OTHER
    REQUESTED_BY: 'Vyžádáno',
    OK: 'OK',
    ERROR: 'ERROR'
};
