lang = {
    DEFAULT: (key) => `${key} haz nut been twanswated fow en-OwO yet.`,
    DEFAULT_LANGUAGE: 'Defauwt Wanguage',
    // PREFIX COMMAND
    PREFIX_REMINDER: (prefix = `@${this.client.user.tag}`) => `Cuwwent pwefix${Array.isArray(prefix) ?
        `es on this sewvew awe: ${prefix.map(pre => `\`${pre}\``).join(', ')}` :
        ` in this sewvew is set to: \`${prefix}\``
        }`,
    PREFIX_SET: (prefix) => `Pwefix haz been changed to \`${prefix}\``,
    CURRENT_PREFIX: (cprefix) => `Cuwwent pwefix is: \`${cprefix}\``,
    PREFIX_DESCRIPTION: 'Changes sewvews pwefix/shows cuwwent pwefix',
    PREFIX_LENGTH: '**You cannut set pwefix wongew than 10 chawactews!**',
    // SHIT
    COOLDOWN_TITLE: 'Coowdown',
    COOLDOWN: (remaining) => `You haz to wait ${remaining} second${remaining === 1 ? '' : 's'} mowe.`,
    COMMAND_DISABLED_SERVER: 'This command haz been disabwed on this sewvew.',
    COMMAND_DISABLED_GLOBAL: 'This command is cuwwentwy nut avaiwabwe.',
    MISSING_BOTPERMS: (missing) => `I dont haz wequiwed pewmissions to compwete this command, missing: **${missing}**.`,
    NSFW: 'This command can onwy be used in NSFW channews!',
    NO_PERMISSIONS: 'You dont haz pewmissions to use this command!',
    MISSING_REQUIRED_SETTINGS: (settings) => `This sewvew is missing da **${settings.join(', ')}** sewvew setting${settings.wength !== 1 ? 's' : ''} and thus this command cannut compwete.`,
    RUNIN: (types) => `This command is onwy avaiwabwe in \`${types}\` channews!`,
    RUNIN_NONE: (name) => `Command \`${name}\` is nut configuwed to wun in any channew.`,
    // EVAL
    EVAL_DESCRIPTION: 'Evawuates given code',
    EVAL_ERROR: (time, output, type) => `**Ewwow**:${output}\n**Type**:${type}\n${time}`,
    EVAL_OUTPUT: (time, output, type) => `**Output**:${output}\n**Type**:${type}\n${time}`,
    EVAL_SENDFILE: (time, type) => `Output was too wong... sent da wesuwt as a fiwe.\n**Type**:${type}\n${time}`,
    EVAL_CONSOLE: (time, type) => `Output was too wong... sent da wesuwt to consowe.\n**Type**:${type}\n${time}`,
    // PING
    PING: '**Pong!**\nWoundtwip took: `Cawcuwating...`.\nHeawtbeat: `Cawcuwating...`.\nDatabase: `Cawcuwating...`.\nWEST: `Cawcuwating...`.',
    PONG: (diff, ping, db, rest) => `**Pong!**\nWoundtwip took: \`${diff}ms\`.\nHeawtbeat: \`${ping}ms\`.\nDatabase: \`${db}ms\`.\nWEST: \`${rest}\`.`,
    PING_DESCRIPTION: 'Pong!',
    // INVITE
    INVITE_DESCRIPTION: 'Invite Bass to uuw sewvew',
    BASS_INVITE: 'Invite bass to uuw sewvew!',
    // INFO
    INFO_DESCRIPTION: 'Info about Bass',
    // HELP
    HELP_DESCRIPTION: 'This message',
    HELP_NO_EXTENDED: 'No extended hewp avaiwabwe.',
    HELP_USAGE: (usage) => `Usage :: ${usage}`,
    HELP_EXTENDED: 'Extended Hewp ::',
    HELP_BOT_OWNER_ONLY: 'Bot Ownew',
    HELP_MANAGE_GUILD: 'Manage sewvew',
    HELP_SERVER_OWNER: 'Sewvew Ownew',
    HELP_SYNTAX: (prefix) => `${prefix}command - Descwiption *(Wequiwed pewmissions)*\nTo get infowmations about command usage do ${prefix}command and it wiww output vawid usage\nFow exampwe: ${prefix}volume`,
    // HELP_SYNTAX: (prefix) => `${prefix}command - Description *(Required permissions)*\nTo get informations about command usage do ${prefix}help (commandname)\nUsing command that requires args without giving them will also give command usage info`,
    HELP_COMMANDS_STRING: 'Commands',
    HELP_COMMAND_NOT_FOUND: (command) => `Command \`${command}\` was nut found.`,
    HELP_TITLE: 'Bass hewp',
    HELP_LINKS: 'Winks',
    HELP_SUPPORT_SERVER: 'Suppowt Sewvew',
    HELP_INVITE: 'Invite',
    HELP_VOTE: 'Vote',
    // STATS
    STATS_DESCRIPTION: 'Shows stats about Bass',
    CLUSTER: 'Cwustew',
    ERROR: 'EWWOW',
    SHARDS: 'Shawds',
    SERVERS: 'Sewvews',
    USERS: 'Usews',
    CONNECTIONS: 'Connections',
    PLAYERS: 'Pwayews',
    TOTAL: 'Totaw',
    CLUSTERS: 'Cwustews',
    // EVENTS_RECIEVED: Events recieved
    // COMMANDS_USED: Commands used
    EVENTS_RECIEVED: 'Events',
    COMMANDS_USED: 'Commands',
    MESSAGES_RECIEVED: 'Messages W',
    MESSAGES_SENT: 'Messages S',
    TOOK: (time) => `Took ${time}`,
    STATS: 'Bass Stats',
    // LANG
    LANG_NOT_FOUND: (lang, langsavailable) => `Wanguage \`${lang}\` was nut found.\nAvaiwabwe wanguages: \`${langsavailable}\``,
    LANG_LANGUAGE_SET: (lang) => `Wanguage haz been changed to \`${lang}\`!`,
    CURRENT_LANGUAGE: (clang, langsavailable) => `**Cuwwent wanguage is:** \`${clang}\`\n\nAvaiwabwe wanguages: \`${langsavailable}\``,
    LANG_DESCRIPTION: 'Changes sewvew wanguage/shows cuwwent wanguage',
    // TRANSLATORS / CONTRIBUTORS
    TRANSLATORS_DESCRIPTION: 'Shows evewy twanswatow that hewped twanswating Bass to othew wanguages',
    CONTRIBUTORS_DESCRIPTION: 'Shows evewyone that contwibuted to da Bass pwoject',
    // SAY
    SAY_DESCRIPTION: 'Bass wepeats given message',
    // SHARD
    SHARD_DESCRIPTION: 'Shows info about shawds/cwustews',
    EMBED_SHARD_DESCRIPTION: (shard, shards, cluster, clusters) => `This sewvew wuns on shawd \`${shard}/${shards}\` and cwustew \`${cluster}/${clusters}\``,
    // SUPPORT
    BASS_SUPPORT_SERVER: 'Bass suppowt sewvew',
    // MUSIC
    NODE_BUSY: 'Sowwy, but audio nude on this sewvew **is cuwwentwy busy**, pwease wait a few seconds and twy again.',
    NODE_NOTHING_PLAYING: '**Nothing is pwaying on this sewvew.**\nMaybe pway something?',
    NODE_NOTHING_PLAYED: '**Nothing was pwayed.**',
    NODE_PROCESSING: 'Audio nude is pwocessing uuw wequest...',
    H4DEEP_DESCRIPTION: 'Toggwes 4deep audio fiwtew',
    NODE_4DEEP_ENABLED: '**Enabwed fiwtew** `4deep`.',
    NODE_4DEEP_DISABLED: '**Disabwed fiwtew** `4deep`.',
    H8D_DESCRIPTION: 'Toggwes 8D audio fiwtew',
    NODE_8D_ENABLED: '**Enabwed fiwtew** `8D`.',
    NODE_8D_DISABLED: '**Disabwed fiwtew** `8D`.',
    ECHO_DESCRIPTION: 'Toggwes echo audio fiwtew',
    NODE_ECHO_ENABLED: '**Enabwed fiwtew** `Echo`.',
    NODE_ECHO_DISABLED: '**Disabwed fiwtew** `Echo`.',
    NIGHTCORE_DESCRIPTION: 'Toggwes nightcowe audio fiwtew',
    NODE_NIGHTCORE_ENABLED: '**Enabwed fiwtew** `Nightcowe`.',
    NODE_NIGHTCORE_DISABLED: '**Disabwed fiwtew** `Nightcowe`.',
    VAPORWAVE_DESCRIPTION: 'Toggwes vapowwave audio fiwtew',
    NODE_VAPORWAVE_ENABLED: '**Enabwed fiwtew** `Vapowwave`.',
    NODE_VAPORWAVE_DISABLED: '**Disabwed fiwtew** `Vapowwave`.',
    CHORUS_DESCRIPTION: 'Toggwes chowus audio fiwtew',
    NODE_CHORUS_ENABLED: '**Enabwed fiwtew** `Chowus`.',
    NODE_CHORUS_DISABLED: '**Disabwed fiwtew** `Chowus`.',
    KARAOKE_DESCRIPTION: 'Toggwes kawaoke audio fiwtew',
    NODE_KARAOKE_ENABLED: '**Enabwed fiwtew** `Kawaoke`.',
    NODE_KARAOKE_DISABLED: '**Disabwed fiwtew** `Kawaoke`.',
    PULSATOR_DESCRIPTION: 'Toggwes puwsatow audio fiwtew',
    NODE_PULSATOR_ENABLED: '**Enabwed fiwtew** `Puwsatow`.',
    NODE_PULSATOR_DISABLED: '**Disabwed fiwtew** `Puwsatow`.',
    TREMOLO_DESCRIPTION: 'Toggwes twemowo audio fiwtew',
    NODE_TREMOLO_ENABLED: '**Enabwed fiwtew** `Twemowo`.',
    NODE_TREMOLO_DISABLED: '**Disabwed fiwtew** `Twemowo`.',
    HSURROUND_DESCRIPTION: 'Toggwes suwwound audio fiwtew',
    NODE_SURROUND_ENABLED: '**Enabwed fiwtew** `Suwwound`.',
    NODE_SURROUND_DISABLED: '**Disabwed fiwtew** `Suwwound`.',
    BITRATE_DESCRIPTION: 'Changes music bitwate/quawity',
    NODE_CHANGED_BITRATE: (amount) => `Bitwate haz been changed to \`${amount}kbps\``,
    NODE_INVALID_BITRATE: 'Pwease give a pwopew bitwate fwom `8` to `512` (kbps)',
    CLEAR_DESCRIPTION: 'Cweaws queue',
    CLEARED_QUEUE: 'Queue haz been cweawed.',
    LOOP_DESCRIPTION: 'Woops cuwwent song/queue',
    LOOP_SONG: '**Enabwed song woop.**',
    LOOP_QUEUE: '**Enabwed queue woop.**',
    LOOP_ALREADY_SONG: 'Song is awweady wooped!',
    LOOP_ALREADY_QUEUE: 'Queue is awweady wooped!',
    LOOP_DISABLED: '**Disabwed woop.**',
    LOOP_INVALID: (prefix) => `**Pwease give a pwopew woop type** \`(0 - disabwe, 1 - song, 2 - queue)\`\nFow exampwe: \`${prefix}loop 2\``,
    NOWPLAYING_DESCRIPTION: 'Shows cuwwentwy pwaying song',
    NOWPLAYING: 'Now Pwaying',
    PAUSE_DESCRIPTION: 'Pauses song',
    PAUSED: '**Paused.**',
    RESUME_DESCRIPTION: 'Wesumes song',
    RESUMED: '**Wesumed.**',
    SHUFFLE_DESCRIPTION: 'Shuffwes queue',
    SHUFFLE_SHUFFLING: '**Shuffwing queue...**',
    SHUFFLE_SHUFFLED: '**Shuffwed queue.**',
    QUEUE_DESCRIPTION: 'Shows cuwwent song queue',
    QUEUE_FETCHING: '**Fetching queue...**',
    QUEUE_MORE: (length) => `*.. And ${length} mowe*`,
    QUEUE_NOWPLAYING: 'Now pwaying',
    QUEUE_UPNEXT: 'Up next',
    QUEUE_NOTHING: '**Nothing**',
    QUEUE_LENGTH: 'Queue wength:',
    QUEUE_FILTERS: 'Fiwtews:',
    QUEUE_BASS_STRENGTH: 'Bass Stwength:',
    QUEUE_LOOP: '**Woop:**',
    QUEUE_SONG: 'Song:',
    QUEUE_YES: 'yes',
    QUEUE_NO: 'nu',
    QUEUE: 'Queue:',
    SKIP_DESCRIPTION: 'Skips cuwwentwy pwaying song',
    SKIPPED: 'Skipped',
    STOP_DESCRIPTION: 'Stops pwaying, cweaws queue and weaves voice channew',
    STOPPED: 'Stopped.',
    PREV_DESCRIPTION: 'Shows wecentwy pwayed song',
    RECENTLY_PLAYED: 'Wecentwy pwayed:',
    VOLUME_DESCRIPTION: 'Changes vowume',
    VOLUME_CHANGED: (prev, amount) => `**Vowume haz been changed fwom \`${prev}%\` to \`${amount}%\`.**`,
    VOLUME_SAME: (amount) => `**Vowume is awweady set to \`${amount}%\`!**`,
    GIVE_PROPER_VOLUME: (current) => `Pwease give a pwopew vowume fwom 0 to 500 (%)\nCuwwent vowume is: \`${current}%\``,
    BASS_DESCRIPTION: 'Changes bass boost stwength',
    GIVE_PROPER_BASS: (current) => `Pwease give a pwopew bass boost fwom 0 to 60 (dB)\nCuwwent bass boost is: \`+${current}dB\``,
    NODE_BASS_CHANGED_DONATOR: (amount) => `**Changed bass boost stwength to** \`+${amount}dB\`\nThank uu fow suppowting Bass!`,
    PLAY_DESCRIPTION: 'Pways song',
    JOINING_VC_ERROR: 'An unknuwn ewwow occouwed upon twying to join uuw voice channew.\nPwease twy again.',
    QUEUED: (url, title) => `Added [${title}](${url}) to queue.`,
    QUEUED_NOW: (url, title) => `[${title}](${url}) wiww nuw pway.`,
    QUEUE_ENDED: 'Queue ended, i haz weft da voice channew.',
    PLAYING_ERROR: (error) => `Ewwow occuwed whiwe twying to pway.\nEwwow message: \`${error}\``,
    PLAYING_EVENT_WITH: (bass, volume, bitrate, filters) => `Bitwate: \`${bitrate}kbps\`, Vowume: \`${volume}%\`\nFiwtews appwied: *${filters.join(', ') || '*-*'}*\nBass Boost stwength: \`+${bass}dB\``,
    PLAY_NO_SONG: 'Pwease give name ow UWW of song uu want to pway.',
    PLAY_NO_VC: 'You awe nut in a voice channew.',
    PLAY_OTHER_VC: 'You awe nut in same voice channew as me. Pwease join my voice channew and twy again.',
    PLAY_NO_PERMS_SPEAK: 'I do nut haz pewmissions to speak in uuw voice channew.',
    PLAY_NO_PERMS_CONNECT: 'I do nut haz pewmissions to join uuw voice channew.',
    SEARCHING_ERROR: (error) => `Ewwow occuwed whiwe seawching.\nEwwow message: \`${error}\``,
    SEARCHING_NOT_FOUND: 'No wesuwts found fow uuw seawch quewy.',
    PLAY_WRONGURL: 'UWW You pwovided seems to be wwong.',
    PLAY_PROCESSING: 'Pwocessing...',
    PLAY_BACKEND_ERROR: 'Backend fow pwocessing seawch wesuwts/pwaywists seems to be down ow wetuwned an ewwow.\nPwease send this infowmation to ouw suppowt sewvew at **https://discord.gg/By3bvFc**!',
    PLAY_QUEUED_PLAYLIST: (size) => `Woaded ${size} songs.`,
    LEAVING_VC: 'Stopping pwaying and weaving voice channew in 15 seconds if nu one wiww join.',
    LEFT_VC: 'I haz stopped pwaying and weft da voice channew due to inactivity.',
    // SUPPORT
    SUPPORT_DESCRIPTION: 'Suppowt sewvew fow hewp with Bass',
    // TTS
    TTS_DESCRIPTION: 'Sends Text to Speech in fiwe',
    TTS_WRONG_LANG: (langs, prefix) => `**Pwease give suppowted wanguage!**\nSuppowted wanguages: \`${langs.join(', ')}\`\nExampwe usage: \`${prefix}tts Hewwo | en\``,
    TTS_ERROR: 'Ewwow occuwed whiwe getting da fiwe.',
    TTS_WRONG_TXT_LENGTH: 'Text wength must be gweatew than 0 chawactews and must nut exceed 200 chawactews.',
    TTS_NO_ARGS: (prefix, langs) => `**Pwease give text and wanguage to genewate tts fow.**\nExampwe usage: \`${prefix}tts Hewwo | en\`\nAvaiwabwe wanguages: \`${langs.join(', ')}\``,
    // RELOAD
    NONE_VC: 'You haz to be in my voice channew to use that command.',
    NONE_NVC: 'I cannut join uuw voice channew!',
    NONE_NOVC: 'You awe nut in voice channew!',
    NONE_VCFULL: 'Youw voice channew is fuww!',
    // RELOAD
    RELOAD_DESCRIPTION: 'Wewoads Bass',
    RELOADED: 'Wewoaded',
    RELOADED_MESSAGE: (time) => `Bass haz been successfuwwy wewoaded in ${time}.`,
    // VOTE
    VOTE_DESCRIPTION: 'Checks uuw vote status/gives vote wink',
    YOU_VOTED: 'You voted!',
    YOU_DIDNT_VOTE: 'You didn\'t vote!',
    VOTED_MESSAGE: (mention, date, votes) => `You voted fow Bass in da wast 12 houws!\nThank uu, ${mention} fow suppowting Bass by voting!\nYou voted at: \`${date}\`\nYou voted fow Bass ${votes} times.\n\n[Vote wink](https://top.gg/bot/590948209925423123/vote)`,
    NOT_VOTED_MESSAGE: (date, votes) => `You didn't vote fow Bass in da wast 12 houws :(\nYouw watest vote was at: \`${date}\`\nYou voted fow Bass ${votes} times.\n\nYou can vote fow Bass [hewe](https://top.gg/bot/590948209925423123/vote).`,
    
    
    // OTHER
    REQUESTED_BY: 'Wequested by',
    OK: 'OK',
    ERROR: 'EWWOW'
};
