lang = {
    DEFAULT: (key) => `${key} non è stato ancora tradotto in it-IT.`,
    DEFAULT_LANGUAGE: 'Lingua Predefinita',
    // PREFIX COMMAND
    PREFIX_REMINDER: (prefix = `@${this.client.user.tag}`) => `Prefiss${Array.isArray(prefix) ?
        `i correnti in questo server sono: ${prefix.map(pre => `\`${pre}\``).join(', ')}` :
        `o corrente in questo server è impostato su: \`${prefix}\``
    }`,
    PREFIX_SET: (prefix) => `Il prefisso è stato cambiato in \`${prefix}\``,
    CURRENT_PREFIX: (cprefix) => `Prefisso corrente: \`${cprefix}\``,
    PREFIX_DESCRIPTION: 'Cambia il prefisso del server/mostra il prefisso corrente',
    PREFIX_LENGTH: '**Il prefisso non deve superare i 10 caratteri!**',
    // SHIT
    COOLDOWN_TITLE: 'Tempo di attesa',
    COOLDOWN: (remaining) => `Devi aspettare ${remaining} second${remaining === 1 ? 'o' : 'i'} per eseguire un altro comando.`,
    COMMAND_DISABLED_SERVER: 'Questo comando è stato disabilitato in questo server.',
    COMMAND_DISABLED_GLOBAL: 'Questo comando non è attualmente disponibile.',
    MISSING_BOTPERMS: (missing) => `Non ho i permessi necessari per completare questo comando, missing: **${missing}**.`,
    NSFW: 'Questo comando può essere utilizzato solo nei canali NSFW!',
    NO_PERMISSIONS: 'Non hai i permessi per usare questo comando!',
    MISSING_REQUIRED_SETTINGS: (settings) => `Nel server manca il **${settings.join(', ')}** impostazione del server${settings.length !== 1 ? '' : ''} e quindi questo comando non può essere completato.`,
    RUNIN: (types) => `Questo comando è disponibile solo in \`${types}\` canali!`,
    RUNIN_NONE: (name) => `Il comando \`${name}\` non è configurato per funzionare in qualunque canale.`,
    // EVAL
    EVAL_DESCRIPTION: 'Valuta il codice dato',
    EVAL_ERROR: (time, output, type) => `**Errore**:${output}\n**Tipo**:${type}\n${time}`,
    EVAL_OUTPUT: (time, output, type) => `**Output**:${output}\n**Tipo**:${type}\n${time}`,
    EVAL_SENDFILE: (time, type) => `L'Output era troppo lungo... il risultato è stato inviato come file.\n**Tipo**:${type}\n${time}`,
    EVAL_CONSOLE: (time, type) => `L'Output era troppo lungo... il risultato è stato invitato alla console.\n**Tipo**:${type}\n${time}`,
    // PING
    PING: '**Pong!**\nRoundtrip took: \`Calcolando...\`.\nHeartbeat: \`Calcolando...\`.\nDatabase: \`Calcolando...\`.\nREST: \`Calcolando...\`.',
    PONG: (diff, ping, db, rest) => `**Pong!**\nRoundtrip took: \`${diff}ms\`.\nHeartbeat: \`${ping}ms\`.\nDatabase: \`${db}ms\`.\nREST: \`${rest}\`.`,
    PING_DESCRIPTION: 'Pong!',
    // INVITE
    INVITE_DESCRIPTION: 'Invita Bass nel tuo server',
    BASS_INVITE: 'Invita bass nel tuo server!',
    // INFO
    INFO_DESCRIPTION: 'Info su Bass',
    // HELP
    HELP_DESCRIPTION: 'Questo messaggio',
    HELP_NO_EXTENDED: 'Guida estesa non disponibile.',
    HELP_USAGE: (usage) => `Uso :: ${usage}`,
    HELP_EXTENDED: 'Guida estesa ::',
    HELP_BOT_OWNER_ONLY: `Proprietario del Bot`,
    HELP_MANAGE_GUILD: `Gestire Server`,
    HELP_SERVER_OWNER: `Proprietario del Server`,
    HELP_SYNTAX: (prefix) => `${prefix}comando - Descrizione *(Permessi richiesti)*\nPer ricevere informazioni sull'uso correto di un comando fai ${prefix}comando è apparira l'utilizzo corretto\nPer esempio: ${prefix}volume`,
    //HELP_SYNTAX: (prefix) => `${prefix}command - Description *(Required permissions)*\nTo get informations about command usage do ${prefix}help (commandname)\nUsing command that requires args, without giving them will also give command usage info`,
    HELP_COMMANDS_STRING: `Comandi`,
    HELP_COMMAND_NOT_FOUND: (command) => `Comando \`${command}\` non trovato.`,
    HELP_TITLE: 'Bass aiuto',
    HELP_LINKS: 'Links',
    HELP_SUPPORT_SERVER: 'Server di Supporto',
    HELP_INVITE: 'Invita',
    HELP_VOTE: 'Vote',
    // STATS
    STATS_DESCRIPTION: 'Mostra le statistiche su Bass',
    CLUSTER: 'Cluster',
    ERROR: 'Errore',
    SHARDS: 'Shards',
    SERVERS: 'Server',
    USERS: 'Utenti',
    CONNECTIONS: 'Connessioni',
    PLAYERS: 'Riproduzioni',
    TOTAL: 'Totale',
    CLUSTERS: 'Clusters',
    //EVENTS_RECIEVED: 'Events recieved',
    //COMMANDS_USED: 'Commands used',
    EVENTS_RECIEVED: 'Eventi',
    COMMANDS_USED: 'Comando\i',
    MESSAGES_RECIEVED: 'Messaggi R',
    MESSAGES_SENT: 'Messaggi S',
    TOOK: (time) => `Took ${time}`,
    STATS: 'Statistiche Bass',
    // LANG
    LANG_NOT_FOUND: (lang, langsavailable) => `La lingua \`${lang}\` non è stata trovata.\nLingue Disponibili: \`${langsavailable}\``,
    LANG_LANGUAGE_SET: (lang) => `La lingua è stata cambiata in \`${lang}\`!`,
    CURRENT_LANGUAGE: (clang, langsavailable) => `**Lingua corrente:** \`${clang}\`\n\nLingue Disponibili: \`${langsavailable}\``,
    LANG_DESCRIPTION: 'Cambia la lingua del server/mostra la lingua corrente',
    // TRANSLATORS / CONTRIBUTORS
    TRANSLATORS_DESCRIPTION: 'Mostra tutti i traduttori che hanno aiutato nella traduzione di Bass in altre lingue',
    CONTRIBUTORS_DESCRIPTION: 'Mostra tutti coloro che hanno contribuito al progetto Bass',
    // SAY
    SAY_DESCRIPTION: 'Bass ripete il messaggio dato',
    // SHARD
    SHARD_DESCRIPTION: 'Mostra info sui shards/clusters',
    EMBED_SHARD_DESCRIPTION: (shard, shards, cluster, clusters) => `Questo server funziona sul shard \`${shard}/${shards}\` e cluster \`${cluster}/${clusters}\``,
    // SUPPORT
    BASS_SUPPORT_SERVER: 'Server di supporto Bass',
    // MUSIC
    NODE_BUSY: `Scusa, ma l'audio node in questo server è **attualmente occupato**, perfavore attenti qualche secondo e riprova nuovamente.`,
    NODE_NOTHING_PLAYING: `**Non c'è niente in riproduzione in questo server.**\nMagari riproduci qualcosa?`,
    NODE_NOTHING_PLAYED: '**Non è stato riprodotto niente.**',
    NODE_PROCESSING: 'Audio node sta elaborando la tua richiesta...',
    H4DEEP_DESCRIPTION: 'Attiva il filtro audio 4deep',
    NODE_4DEEP_ENABLED: '**Filtro abilitato** `4deep`.',
    NODE_4DEEP_DISABLED: '**Filtro disabilitato** `4deep`.',
    H8D_DESCRIPTION: 'Attiva il filtro audio 8D',
    NODE_8D_ENABLED: '**Filtro abilitato** `8D`.',
    NODE_8D_DISABLED: '**Filtro disabilitato** `8D`.',
    ECHO_DESCRIPTION: 'Attiva il filtro audio echo',
    NODE_ECHO_ENABLED: '**Filtro abilitato** `Echo`.',
    NODE_ECHO_DISABLED: '**Filtro disabilitato** `Echo`.',
    NIGHTCORE_DESCRIPTION: 'Attiva il filtro audio nightcore',
    NODE_NIGHTCORE_ENABLED: '**Filtro abilitato** `Nightcore`.',
    NODE_NIGHTCORE_DISABLED: '**Filtro disabilitato** `Nightcore`.',
    VAPORWAVE_DESCRIPTION: 'Attiva il filtro audio vaporwave',
    NODE_VAPORWAVE_ENABLED: '**Filtro abilitato** `Vaporwave`.',
    NODE_VAPORWAVE_DISABLED: '**Filtro disabilitato** `Vaporwave`.',
    CHORUS_DESCRIPTION: 'Attiva il filtro audio chorus',
    NODE_CHORUS_ENABLED: '**Filtro abilitato** `Chorus`.',
    NODE_CHORUS_DISABLED: '**Filtro disabilitato** `Chorus`.',
    KARAOKE_DESCRIPTION: 'Attiva il filtro audio karaoke',
    NODE_KARAOKE_ENABLED: '**Filtro abilitato** `Karaoke`.',
    NODE_KARAOKE_DISABLED: '**Filtro disabilitato** `Karaoke`.',
    PULSATOR_DESCRIPTION: 'Attiva il filtro audio pulsator',
    NODE_PULSATOR_ENABLED: '**Filtro abilitato** `Pulsator`.',
    NODE_PULSATOR_DISABLED: '**Filtro disabilitato** `Pulsator`.',
    TREMOLO_DESCRIPTION: 'Attiva il filtro audio tremolo',
    NODE_TREMOLO_ENABLED: '**Filtro abilitato** `Tremolo`.',
    NODE_TREMOLO_DISABLED: '**Filtro disabilitato** `Tremolo`.',
    HSURROUND_DESCRIPTION: 'Attiva il filtro audio surround',
    NODE_SURROUND_ENABLED: '**Filtro abilitato** `Surround`.',
    NODE_SURROUND_DISABLED: '**Filtro disabilitato** `Surround`.',
    H8BIT_DESCRIPTION: 'Attiva il filtro audio 8bit',
    NODE_8BIT_ENABLED: '**Filtro abilitato** `8-bit`.',
    NODE_8BIT_DISABLED: '**Filtro disabilitato** `8-bit`.',
    BITRATE_DESCRIPTION: 'Cambia il bitrate/qualita della musica',
    NODE_CHANGED_BITRATE: (amount) => `Il bitrate è stato impostato a \`${amount}kbps\``,
    NODE_INVALID_BITRATE: 'Perfavore fornisci un bitrate da \`8\` a \`512\` (kbps)',
    CLEAR_DESCRIPTION: 'Cancella la coda',
    CLEARED_QUEUE: 'La coda è stata cancellata.',
    LOOP_DESCRIPTION: 'Metti in loop la canzone/coda corrente',
    LOOP_SONG: '**Abilitato il loop della canzone.**',
    LOOP_QUEUE: '**Abilitato il loop della coda.**',
    LOOP_ALREADY_SONG: 'La canzone è gia in loop!',
    LOOP_ALREADY_QUEUE: 'La coda è gia in loop!',
    LOOP_DISABLED: '**Disabilitato il loop.**',
    LOOP_INVALID: (prefix) => `**Perfavore fornisci un tipo di loop corretto** \`(0 - disabilita, 1 - canzone, 2 - coda)\`\nPer esempio: \`${prefix}loop 2\``,
    NOWPLAYING_DESCRIPTION: 'Mostra la canzone attualmente in riproduzione',
    NOWPLAYING: 'In riproduzione',
    PAUSE_DESCRIPTION: 'Metti in pausa la canzone',
    PAUSED: '**In pausa.**',
    RESUME_DESCRIPTION: 'Riprendi la riproduzione della canzone',
    RESUMED: '**Ripresa.**',
    SHUFFLE_DESCRIPTION: 'Mischia la coda',
    SHUFFLE_SHUFFLING: '**Mischiando la coda...**',
    SHUFFLE_SHUFFLED: '**Coda mischiata.**',
    QUEUE_DESCRIPTION: 'Mosta le canzoni in coda',
    QUEUE_FETCHING: '**Recuperando la coda...**',
    QUEUE_MORE: (length) => `*.. e ${length} in piu*`,
    QUEUE_NOWPLAYING: 'Riproduzione in corso',
    QUEUE_UPNEXT: 'Prossime',
    QUEUE_NOTHING: '**Niente**',
    QUEUE_LENGTH: 'Lunghezza coda:',
    QUEUE_FILTERS: 'Filtri:',
    QUEUE_BASS_STRENGTH: 'Potenza Bass:',
    QUEUE_LOOP: '**Loop:**',
    QUEUE_SONG: 'Canzone:',
    QUEUE_YES: 'si',
    QUEUE_NO: 'no',
    QUEUE: 'Coda:',
    SKIP_DESCRIPTION: 'Saltata la canzone corrente',
    SKIPPED: 'Saltato',
    STOP_DESCRIPTION: 'Interrompi la riproduzione, cancella la coda e abbandona il canale vocale',
    STOPPED: 'Stoppato.',
    PREV_DESCRIPTION: 'Mostra le canzoni riprodotte di recente',
    RECENTLY_PLAYED: 'Riproduzione recente:',
    VOLUME_DESCRIPTION: 'Cambia il volume',
    VOLUME_CHANGED: (prev, amount) => `**Il volume è stato cambiato da \`${prev}%\` a \`${amount}%\`.**`,
    VOLUME_SAME: (amount) => `**Il volume è gia impostato a \`${amount}%\`!**`,
    GIVE_PROPER_VOLUME: (current) => `Perfavore inserisci un volume da 0 a 500 (%)\nVolume corrente: \`${current}%\``,
    BASS_DESCRIPTION: 'Cambia la potenza del bass boost',
    GIVE_PROPER_BASS: (current) => `Perfavore inserisci un bass boost da 0 a 60 (dB)\nBass Boost corrente: \`+${current}dB\``,
    NODE_BASS_CHANGED_DONATOR: (amount) => `**Potenza del bass boost cambiata a** \`+${amount}dB\`\nGrazie per supportare Bass!`,
    PLAY_DESCRIPTION: 'Riproduci canzone',
    JOINING_VC_ERROR: 'Si è verificato un errore sconosciuto nel tentativo di collegarmi al tuo canale vocale.\nPerfavore riprova nuovamente.',
    QUEUED: (url, title) => `Aggiunto [${title}](${url}) alla coda.`,
    QUEUED_NOW: (url, title) => `[${title}](${url}) in riproduzione.`,
    QUEUE_ENDED: 'Coda terminata, ho abbandonato il canale vocale.',
    PLAYING_ERROR: (error) => `Si è verificato un errore durate il tentativo di riproduzione.\nMessaggio di errore: \`${error}\``,
    PLAYING_EVENT_WITH: (bass, volume, bitrate, filters) => `Bitrate: \`${bitrate}kbps\`, Volume: \`${volume}%\`\nFiltri applicati: *${filters.join(', ') || '*-*'}*\nPotenza Bass Boost: \`+${bass}dB\``,
    PLAY_NO_SONG: `Perfavore inserisci un nome o l'URL della canzone che vuoi riprodurre.`,
    PLAY_NO_VC: 'Non sei in un canale vocale.',
    PLAY_OTHER_VC: 'Non sei nello stesso canale vocale con me. Perfavore entra nel mio canale vocale e riprova nuovamente.',
    PLAY_NO_PERMS_SPEAK: 'Non ho i permessi per parlare nel tuo canale vocale.',
    PLAY_NO_PERMS_CONNECT: 'Non ho i permessi per entrare nel tuo canale vocale.',
    SEARCHING_ERROR: (error) => `Si è verificato un errore durante la ricerca.\nMessaggio di errore: \`${error}\``,
    SEARCHING_NOT_FOUND: 'Nessun risultato trovato per la tua ricerca.',
    PLAY_WRONGURL: `L'URL che hai fornito sembra essere sbagliato.`,
    PLAY_PROCESSING: 'Elaborazione...',
    PLAY_BACKEND_ERROR: `Il Backend per l'elaborazione del risultato cercato/playlist sembra essere inattivo o ha riscontrato un errore.\nPerfavore manda questa informazione nel nostro server di supporto **https://discord.gg/By3bvFc**!`,
    PLAY_QUEUED_PLAYLIST: (size) => `Caricate ${size} canzoni.`,
    LEAVING_VC: 'La riproduzione verrà interrotta e usciro dal canale vocale se nessuno entra in 15 secondi.',
    LEFT_VC: 'Ho smesso di riprodurre e ho abbandonato il canale vocale per inattività',
    // SUPPORT
    SUPPORT_DESCRIPTION: 'Server di supporto per aiuto con Bass',
    // TTS
    TTS_DESCRIPTION: 'Manda una sintesi vocale con file',
    TTS_WRONG_LANG: (langs, prefix) => `**Perfavore fornisci una lingua supportata!**\nLingue supportate: \`${langs.join(', ')}\`\nEsempio di utilizzo: \`${prefix}tts Ciao | it\``,
    TTS_ERROR: 'Si è verificato un errore durante la ricezione del file.',
    TTS_WRONG_TXT_LENGTH: 'La lunghezza del testo deve essere superiore a 0 e non deve superare i 200 caratteri.',
    TTS_NO_ARGS: (prefix, langs) => `**Perfavore fornisci un testo e la lingua per generare il tts.**\nEsempio di utilizzo: \`${prefix}tts Ciao | it\`\nLingue Disponibili: \`${langs.join(', ')}\``,
    // IDK
    NONE_VC: 'Devi essere nel mio canale vocale per poter usare questo comando.',
    NONE_NVC: 'Non posso entrare nel tuo canale vocale!',
    NONE_NOVC: 'Non sei in un canale vocale!',
    NONE_VCFULL: 'Il tuo canale vocale è pieno!',
    // RELOAD
    RELOAD_DESCRIPTION: 'Reloads Bass',
    RELOADED: 'Reloaded',
    RELOADED_MESSAGE: (time) => `Bass has been successfully reloaded in ${time}.`,
    // VOTE
    VOTE_DESCRIPTION: 'Checks your vote status/gives vote link',
    YOU_VOTED: 'You voted!',
    YOU_DIDNT_VOTE: 'You didn\'t vote!',
    VOTED_MESSAGE: (mention, date, votes) => `You voted for Bass in the last 12 hours!\nThank you, ${mention} for supporting Bass by voting!\nYou voted at: \`${date}\`\nYou voted for Bass ${votes} times.\n\n[Vote link](https://top.gg/bot/590948209925423123/vote)`,
    NOT_VOTED_MESSAGE: (date, votes) => `You didn't vote for Bass in the last 12 hours :(\nYour latest vote was at: \`${date}\`\nYou voted for Bass ${votes} times.\n\nYou can vote for Bass [here](https://top.gg/bot/590948209925423123/vote).`,



    // OTHER
    REQUESTED_BY: 'Richiesto da',
    OK: 'OK',
    ERROR: 'ERRORE'
};
// Mizen#3909 
